version: '3'

services:
 
  redis:
    image: redis
    ports:
      - 6379:6379

  mongo:
    image: mongo
    ports:
      - 27017:27017

  asym:
    build:
      context: .
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    depends_on:
      - redis
      - mongo
    command: [
      './wait-for-it.sh', 'redis:6379', '-t', '5', '--strict', '--',
      './wait-for-it.sh', 'mongo:27017', '-t', '5', '--strict', '--',
      'node', 'app.js'
    ]